name: Node.js CI with Keploy API Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install --save-dev wait-on

      - name: Run unit and integration tests
        run: npm test

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Start API Server
        run: |
          npm start &
        env:
          MONGODB_URI: mongodb://localhost:27017/test

      - name: Wait for API to be ready
        run: npx wait-on http://localhost:3000/api/holidays

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=00079289-da05-4efd-af7f-3c89fe67ed78 --base-path http://localhost:3000/api/holidays --cloud
